language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"

before_install:
  - pip install hererocks
  - hererocks lua -r^ --$LUA
  - export PATH=$PATH:$PWD/lua/bin
  - luarocks install luacheck
  - luarocks install dkjson --deps-mode=none
  - luarocks install busted

install:
  - luarocks make

script:
  - busted
  - luacheck src spec
